name: Build
description: Build .NET solution and cache restored NuGet packages

inputs:
  configuration:
    description: .NET build configuration
    required: true

runs:
  using: composite
  steps:
    - name: Cache NuGet packages
      uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    - name: Set up .NET SDK
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.x.x

    - name: Restores dependencies
      shell: bash
      run: dotnet restore --locked-mode

    - name: Build solution
      shell: bash
      run: >-
        dotnet build
        --configuration ${{ inputs.configuration }}
        --no-incremental
        --no-restore
        --no-self-contained
