# Copyright (c) 2022 Omar Boukli-Hacene. All rights reserved.
# Distributed under an MIT-style license that can be
# found in the LICENSE file.

# SPDX-License-Identifier: MIT

name: Build
description: Build .NET solution and cache restored NuGet packages

inputs:
  configuration:
    description: .NET build configuration
    required: true

runs:
  using: composite
  steps:
    - name: Cache NuGet packages
      uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        key: >-
          ${{ runner.os }}-nuget-${{
          hashFiles('**/packages.lock.json',
          '.config/dotnet-tools.json')
          }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    - name: Set up .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Restores dependencies
      env:
        DOTNET_NUGET_SIGNATURE_VERIFICATION: "true"
      shell: bash
      run: dotnet restore --locked-mode

    - name: Build solution
      shell: bash
      run: >-
        dotnet build
        --configuration ${{ inputs.configuration }}
        --no-incremental
        --no-restore
        --no-self-contained
