# Copyright (c) Omar Boukli-Hacene. All rights reserved.
# Distributed under an MIT-style license that can be
# found in the LICENSE file.

# SPDX-License-Identifier: MIT

trigger:
  branches:
    include:
    - main
  paths:
    include:
    - src/
    - test/
  pr:
    branches:
      include:
      - main
    paths:
      include:
      - src/
      - test/

strategy:
  matrix:
    linuxLatest:
      imageName: ubuntu-latest
    windowsLatest:
      imageName: windows-latest

pool:
  vmImage: $(imageName)

variables:
  buildConfiguration: Release
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_NUGET_SIGNATURE_VERIFICATION: true

steps:
  - task: UseDotNet@2
    displayName: Use .NET
    useGlobalJson: true

  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      arguments: --configuration $(buildConfiguration)
      command: build
