name: Build and run unit and integration tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Solution build
    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: true
    outputs:
      short-commit-sha: ${{ steps.get-short-commit-sha.outputs.short-commit-sha }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Build release
        uses: ./.github/workflows/composite/dotnet-build
        with:
          configuration: Release

      - name: Create build artifacts archive
        run: tar --create --verbose --file aktabook-build.tar .

      - name: Get short commit SHA
        id: get-short-commit-sha
        run: echo "::set-output name=short-commit-sha::$(git rev-parse --short "$GITHUB_SHA")"

      - name: Upload build artifacts archive
        uses: actions/upload-artifact@v3
        with:
          name: aktabook-build-${{ steps.get-short-commit-sha.outputs.short-commit-sha }}
          path: aktabook-build.tar

  integration-test:
    name: Integration test
    runs-on: ubuntu-latest
    needs: build
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: true

    services:
      sqlserver:
        image: mcr.microsoft.com/mssql/server:2022-latest
        env:
          ACCEPT_EULA: Y
          SA_PASSWORD: ${{ secrets.SQLSERVER_INTEGRATION_TEST_SA_PASSWORD }}
        ports:
          - 1433:1433

    steps:
      - name: Download build artifacts archive
        uses: actions/download-artifact@v3
        with:
          name: aktabook-build-${{ needs.build.outputs.short-commit-sha }}

      - name: Extract build artifacts archive
        run: tar --extract --verbose --file aktabook-build.tar

      - name: Run integration tests
        env:
          AKTABOOK_INTEGRATION_TEST_ENVIRONMENT: Test
          RequesterServiceDbContext__SqlServerConfig__DataSource: 127.0.0.1
          RequesterServiceDbContext__SqlServerConfig__UserID: sa
          RequesterServiceDbContext__SqlServerConfig__Password: ${{ secrets.SQLSERVER_INTEGRATION_TEST_SA_PASSWORD }}
          RequesterServiceDbContext__SqlServerConfig__Encrypt: false
        run: >-
          dotnet test
          --configuration Release
          --filter FullyQualifiedName\~IntegrationTest
          --no-build
          --no-restore

  unit-test:
    name: Unit test
    runs-on: ubuntu-latest
    needs: build
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: true

    steps:
      - name: Download build artifacts archive
        uses: actions/download-artifact@v3
        with:
          name: aktabook-build-${{ needs.build.outputs.short-commit-sha }}

      - name: Extract build artifacts archive
        run: tar --extract --verbose --file aktabook-build.tar

      - name: Run unit tests
        run: >-
          dotnet test
          --no-build
          --configuration Release
          --filter FullyQualifiedName\~UnitTest
