name: Build

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.x.x

      - name: Restores dependencies
        run: dotnet restore

      - name: Build release
        run: >-
          dotnet build
          --no-restore
          --configuration Release

      - name: Run unit tests
        run: >-
          dotnet test
          --no-build
          --configuration Release
          --filter FullyQualifiedName\!~IntegrationTest
