name: Code style check

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    name: Check .NET projects
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.x.x

      - name: Run dotnet format
        run: >-
          dotnet format
          --verify-no-changes
          --verbosity quiet
