# Copyright (c) 2022 Omar Boukli-Hacene. All rights reserved.
# Distributed under an MIT-style license that can be
# found in the LICENSE file.

# SPDX-License-Identifier: MIT

name: Code style check

on:
  pull_request:
    branches:
      - main
    paths:
      - "src/**"
      - "test/**"
  push:
    branches:
      - main
    paths:
      - "src/**"
      - "test/**"

permissions:
  contents: read

jobs:
  build:
    name: Check .NET solution code style
    runs-on: ubuntu-latest

    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: true

    steps:
      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Run dotnet format
        run: >-
          dotnet format
          --verbosity quiet
          --verify-no-changes
