name: Code style check

on:
  pull_request:
    branches:
      - main
    paths:
      - "src/**"
      - "test/**"
  push:
    branches:
      - main
    paths:
      - "src/**"
      - "test/**"

jobs:
  build:
    name: Check .NET solution code style
    runs-on: ubuntu-latest

    steps:
      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.x.x

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Run dotnet format
        run: >-
          dotnet format
          --verbosity quiet
          --verify-no-changes
