name: Integration test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    services:
      sqlserver:
        image: mcr.microsoft.com/mssql/server:2022-latest
        env:
          ACCEPT_EULA: Y
          SA_PASSWORD: ${{ secrets.SQLSERVER_INTEGRATION_TEST_SA_PASSWORD }}
        ports:
          - 1433:1433

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.x.x

      - name: Restore
        run: dotnet restore

      - name: Build
        run: >-
          dotnet build
          --configuration Release
          --no-restore

      - name: Test
        env:
          AKTABOOK_INTEGRATION_TEST_ENVIRONMENT: Test
          RequesterServiceDbContext__SqlServerConfig__DataSource: 127.0.0.1
          RequesterServiceDbContext__SqlServerConfig__UserID: sa
          RequesterServiceDbContext__SqlServerConfig__Password: ${{ secrets.SQLSERVER_INTEGRATION_TEST_SA_PASSWORD }}
          RequesterServiceDbContext__SqlServerConfig__Encrypt: false
        run: >-
          dotnet test
          --configuration Release
          --filter FullyQualifiedName\~IntegrationTest
          --no-build
          --no-restore
