name: Integration test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    services:
      sqlserver:
        image: mcr.microsoft.com/mssql/server:2022-latest
        env:
          ACCEPT_EULA: Y
          SA_PASSWORD: ${{ secrets.SQLSERVER_INTEGRATION_TEST_SA_PASSWORD }}
        options: >-
          --health-cmd "/opt/mssql-tools/bin/sqlcmd -Usa -P ${SA_PASSWORD} -Q SELECT 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 1435:1433

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.x.x

      - name: Restore
        run: dotnet restore

      - name: Build
        run: >-
          dotnet build
          --no-restore
          --configuration Release

      - name: Test
        with:
          RequesterServiceDbContext__SqlServerConfig__DataSource: localhost
          RequesterServiceDbContext__SqlServerConfig__InitialCatalog: aktabook
          RequesterServiceDbContext__SqlServerConfig__UserID: sa
          RequesterServiceDbContext__SqlServerConfig__Password: ${{ secrets.SQLSERVER_INTEGRATION_TEST_SA_PASSWORD }}
        run: >-
          dotnet test
          --no-build
          --configuration Release
          --filter FullyQualifiedName\~IntegrationTest
