name: Lint

on:
  pull_request:
    paths:
      - "**.md"
  push:
    paths:
      - "**.md"
  workflow_dispatch:

permissions: {}

jobs:
  markdownlint:
    name: Markdownlint
    runs-on: ubuntu-latest

    steps:
      - name: Install markdownlint-cli
        run: sudo npm install --global markdownlint-cli

      - name: Check out code
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Run markdownlint
        run: markdownlint .
