# Copyright (c) Omar Boukli-Hacene. All rights reserved.
# Distributed under an MIT-style license that can be
# found in the LICENSE file.

# SPDX-License-Identifier: MIT

name: Publish build output

on:
  pull_request:
    branches:
      - main
    paths:
      - src/**
      - test/**
  push:
    branches:
      - main
    paths:
      - src/**
      - test/**
  workflow_dispatch:

permissions: {}

jobs:
  publish:
    name: Publish for Ubuntu
    runs-on: ubuntu-latest
    env:
      AKTABOOK_DOTNET_FRAMWORK: net6.0
      AKTABOOK_DOTNET_RUNTIME_TARGET: ubuntu.22.04-x64
      AKTABOOK_PUBLISH_PATH_ROOT: ${{ github.workspace }}/publish
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      DOTNET_NUGET_SIGNATURE_VERIFICATION: true

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          cache: true
          cache-dependency-path: |-
            src/**/packages.lock.json
            test/**/packages.lock.json
          global-json-file: global.json

      - name: Restores dependencies
        run: >-
          dotnet restore
          --locked-mode
          --no-cache

      - name: Publish Aktabook.Bus release
        run: >-
          dotnet publish
          ${{ github.workspace }}/src/Aktabook.Bus/Aktabook.Bus.csproj
          --configuration Release
          --framework ${{ env.AKTABOOK_DOTNET_FRAMWORK }}
          --no-restore
          --no-self-contained
          --output ${{ env.AKTABOOK_PUBLISH_PATH_ROOT }}/Aktabook.Bus/
          --runtime ${{ env.AKTABOOK_DOTNET_RUNTIME_TARGET }}

      - name: Publish Aktabook.PublicApi.V1 release
        run: >-
          dotnet publish
          ${{ github.workspace }}/src/Aktabook.PublicApi.V1/Aktabook.PublicApi.V1.csproj
          --configuration Release
          --framework ${{ env.AKTABOOK_DOTNET_FRAMWORK }}
          --no-restore
          --no-self-contained
          --output ${{ env.AKTABOOK_PUBLISH_PATH_ROOT }}/Aktabook.PublicApi.V1/
          --runtime ${{ env.AKTABOOK_DOTNET_RUNTIME_TARGET }}

      - name: Upload bus binaries
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          name: aktabook_bus_${{ env.AKTABOOK_DOTNET_RUNTIME_TARGET }}
          path: ${{ env.AKTABOOK_PUBLISH_PATH_ROOT }}/Aktabook.Bus/

      - name: Upload API binaries
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          name: aktabook_api_${{ env.AKTABOOK_DOTNET_RUNTIME_TARGET }}
          path: ${{ env.AKTABOOK_PUBLISH_PATH_ROOT }}/Aktabook.PublicApi.V1/
