name: JetBrains ReSharper InspectCode

on:
  pull_request:
    branches:
      - main
    paths:
      - "src/**"
      - "test/**"
  push:
    branches:
      - main
    paths:
      - "src/**"
      - "test/**"
  workflow_dispatch:

permissions: {}

jobs:
  inspect-code:
    runs-on: ubuntu-latest

    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          cache: true
          cache-dependency-path: |-
            src/**/packages.lock.json
            test/**/packages.lock.json
          global-json-file: global.json

      # https://www.nuget.org/packages/jetbrains.resharper.globaltools
      - name: Annotate
        uses: JetBrains/ReSharper-InspectCode@v0.3
        with:
          build: True
          mono:
          solution: ./Aktabook.sln
          telemetry-optout: True
          tool-version: "2024.1.0-rc01"
