name: SonarCloud scan

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: 17 21 * * 5
  workflow_dispatch:

jobs:
  build:
    name: Build
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: true
    runs-on: windows-latest

    steps:
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: microsoft

      - name: Install tools
        run: |-
          dotnet tool install --global dotnet-coverage
          dotnet tool install --global dotnet-sonarscanner

      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Restores dependencies
        run: dotnet restore

      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        shell: powershell
        run: |-
          dotnet sonarscanner begin `
          /k:oboukli_aktabook `
          /o:oboukli `
          /d:sonar.cs.vscoveragexml.reportsPaths=coverage.xml `
          /d:sonar.host.url="https://sonarcloud.io" `
          /d:sonar.login=${{ secrets.SONAR_TOKEN }}
          dotnet build ./Aktabook.sln `
          `--configuration Release `
          `--no-incremental `
          `--no-restore
          dotnet coverage collect `
          `--output-format xml `
          `--output coverage.xml `
          dotnet test `
          `--no-build `
          `--configuration Release `
          `--filter FullyQualifiedName\!~IntegrationTest
          dotnet sonarscanner end `
          /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
