name: SonarCloud scan

on:
  pull_request:
  push:
  schedule:
    - cron: 17 21 * * 5

jobs:
  build:
    name: Build
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: true
    runs-on: windows-latest

    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: microsoft

      - name: Install SonarCloud scanner
        run: dotnet tool install --global dotnet-sonarscanner

      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Restores dependencies
        run: dotnet restore

      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        shell: powershell
        run: |-
          dotnet sonarscanner begin `
          /k:oboukli_aktabook `
          /o:oboukli `
          /d:sonar.login=${{ secrets.SONAR_TOKEN }} `
          /d:sonar.host.url="https://sonarcloud.io"
          dotnet build ./Aktabook.sln `
          `--configuration Release `
          `--no-restore
          dotnet sonarscanner end `
          /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
